---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    ignore:
      # These are included by k8s.io/client-go
      - dependency-name: k8s.io/api
      - dependency-name: k8s.io/apimachinery
    open-pull-requests-limit: 10
