---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: submariner-bot
  labels:
    app: submariner-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submariner-bot
  template:
    metadata:
      labels:
        app: submariner-bot
    spec:
      containers:
        - name: submariner-bot
          image: quay.io/submariner/submariner-bot:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
