---
name: Linting

on:
  pull_request:

jobs:
  gitlint:
    name: Commit Message(s)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0
      - name: Run gitlint
        run: make gitlint

  golangci-lint:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Run golangci-lint
        run: make golangci-lint

  markdownlint:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Run markdownlint
        run: make markdownlint

  yaml-lint:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Run yamllint
        run: make yamllint
